## Word Embedding

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size = 10000

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3874, 1639, 3347, 8558],
 [3874, 1639, 3347, 3581],
 [3874, 7326, 3347, 3344],
 [2777, 4058, 6614, 1365, 1232],
 [2777, 4058, 6614, 1365, 4166],
 [4589, 3874, 7261, 3347, 5874],
 [8123, 5876, 310, 1365]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3874 1639 3347 8558]
 [   0    0    0    0 3874 1639 3347 3581]
 [   0    0    0    0 3874 7326 3347 3344]
 [   0    0    0 2777 4058 6614 1365 1232]
 [   0    0    0 2777 4058 6614 1365 4166]
 [   0    0    0 4589 3874 7261 3347 5874]
 [   0    0    0    0 8123 5876  310 1365]]


In [13]:
## feature representation
dim=10

In [20]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [21]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 195ms/step


array([[[ 1.90520398e-02,  2.40709819e-02, -2.58695725e-02,
         -4.27231789e-02,  1.04654208e-02, -3.04149147e-02,
         -1.33432262e-02,  4.83692400e-02,  2.74038203e-02,
          8.97526741e-04],
        [ 1.90520398e-02,  2.40709819e-02, -2.58695725e-02,
         -4.27231789e-02,  1.04654208e-02, -3.04149147e-02,
         -1.33432262e-02,  4.83692400e-02,  2.74038203e-02,
          8.97526741e-04],
        [ 1.90520398e-02,  2.40709819e-02, -2.58695725e-02,
         -4.27231789e-02,  1.04654208e-02, -3.04149147e-02,
         -1.33432262e-02,  4.83692400e-02,  2.74038203e-02,
          8.97526741e-04],
        [ 1.90520398e-02,  2.40709819e-02, -2.58695725e-02,
         -4.27231789e-02,  1.04654208e-02, -3.04149147e-02,
         -1.33432262e-02,  4.83692400e-02,  2.74038203e-02,
          8.97526741e-04],
        [ 1.13075152e-02, -2.32960712e-02, -1.18369237e-02,
          2.49259956e-02, -4.35925834e-02, -3.78676504e-03,
          1.68042518e-02,  1.49309635e-04,  1.695629

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 3874, 1639, 3347, 8558])

In [27]:
# import pandas as pd
model.predict(embedded_docs[0:1])


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step


array([[[-0.02340339, -0.02643274,  0.00685706, -0.02694143,
         -0.03153312, -0.01568644,  0.03043398,  0.0331619 ,
         -0.03790313,  0.041048  ],
        [-0.02340339, -0.02643274,  0.00685706, -0.02694143,
         -0.03153312, -0.01568644,  0.03043398,  0.0331619 ,
         -0.03790313,  0.041048  ],
        [-0.02340339, -0.02643274,  0.00685706, -0.02694143,
         -0.03153312, -0.01568644,  0.03043398,  0.0331619 ,
         -0.03790313,  0.041048  ],
        [-0.02340339, -0.02643274,  0.00685706, -0.02694143,
         -0.03153312, -0.01568644,  0.03043398,  0.0331619 ,
         -0.03790313,  0.041048  ],
        [ 0.01411184, -0.04715885,  0.02051407, -0.03764782,
          0.03258765,  0.00322694, -0.02113148, -0.04717091,
         -0.006122  ,  0.03321569],
        [ 0.01607167, -0.04025158,  0.00635775, -0.01832123,
          0.00182366, -0.02492272, -0.04177504,  0.01575274,
         -0.03230927,  0.02619399],
        [-0.02013846,  0.00027122, -0.01182532,  0.0